### ISSUE TITLE
请教标签页的切换与内容详情加载的问题

### ISSUE THREAD

**Issue by riddle911** [Shaman05/CNodeJs-WXAPP#1]
老哥，仔细阅读了您的代码，加上我自己也在做类似的小程序，有点疑惑还望能解答下：

我是自己有个论坛，然后暴露了各种api出来，目前做的程度是
在header的类别中，通过wx.request获取host.com/api/categories,得到目录名称然后渲染出来，目录切换使用的也是查询e.target.id做的；

主要遇到问题是，我的header里如何做到绑定不同路由呢，是这样：

我现在类别一栏中 设置了两种：一个是 “最新”帖子，其json地址为：host.com/api/recent
另外就是不同版块的json地址： host.com/api/category/{某种特定id}/{版块名称}

这样就涉及到请求不同路由加载内容详情的问题，我看一般类似的程序大家都是请求的单独一个url，通过判断id什么的做不同的路由更改，那你看我现在要是实现切换tab时，请求不同路由，这个应该按什么思路实现呢？网上搜索了好几天都不得要领，还请您指点一二。

**Comment by Shaman05** [comment]
不好意思，我看了几遍你的描述，始终没有get到你具体场景（“主要遇到问题是，我的header里如何做到绑定不同路由”）碰到的问题

**Comment by riddle911** [comment]
emmmm 是我叙述有问题。这么说吧
比如tab标签中设置了如下：
“最新” |  政治  |  军事 |  娱乐...类似的栏目，
其中”最新“的内容详情来自于 www.host.com/api/recent
之后的 政治 军事等 的详情分别来自于  www.host.com/api/category/{某种id}/{栏目名字，政治、军事...}，

这样，当我在几个标签切换时，他们的需要wx.request不同的url，所以问题就是这个不同的url是如何动态的也绑定在每个标签上....因为”最新“和其他栏目的uri不一样....所以不知道怎么操作

**Comment by Shaman05** [comment]
噢噢，这个可以有两个办法
1. 在你获取栏目分类的接口（ host.com/api/categories）里返回这个不同url信息
2. 也可以在你小程序里，按你分类的名称固定配置好这个url
然后点击tab切换的时候调详情列表wx.request就根据每个栏目的url去取就OK了

**Comment by riddle911** [comment]
噢 是这样，
我的栏目分类是动态获取的，因为后台有可能会动，就没写死，所以就得按您说的第一条来做了~
然后想问，不知道您遇到过这个情况没，就是我获取栏目分类接口的时候，同时也把相关的uri给构造出来，并且setdata到data[uri[]]这个里面了，这个操作是在onload里完成的，当时也能打印出来，但是我在其他funciton里试图调用这个值，_self.data.uri时，会报undefined。这个查了半天都不知道怎么回事，有人说和异步有关系，我也没搞明白~

**Comment by Shaman05** [comment]
你应该在获取栏目分类的接口回调里去setData分类信息数据，这样才能保证构造出来的栏目分类里的data-uri是有值的。

**Comment by riddle911** [comment]
嗯 我应该是按照这样操作的，取得栏目数据```category[]```、以及取得```uri[]```都是在wx.request 的回调里进行setdata处理的，奇怪的是我在```wxml```里直接渲染这些数据都可以，但是js调用都不成功.....这个是不是讲道理不会出现的问题？
